#!/usr/bin/env python3
"""
Evaluate a trained anomaly detection model against the CICDDoS2019 dataset.

This script loads an existing model artifact (trained via ``train_with_cic``
or any other training workflow) and evaluates it against the CICDDoS2019
dataset, producing per-attack-type detection rates, confusion matrices,
and LaTeX-ready tables.

Usage::

    # Evaluate the CIC-trained model
    python -m detection_v2.evaluate_cic --model results/cic_training/cicddos_detector.pkl

    # Evaluate with detailed SHAP explanations for top-3 attacks
    python -m detection_v2.evaluate_cic --model model.pkl --explain

    # Compare against live-trained model
    python -m detection_v2.evaluate_cic --model results/live_training/model.pkl
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

from .adapters.cicddos_adapter import (
    ATTACK_CATEGORIES,
    CICDDoS2019Adapter,
    categorise_attack,
)
from .core.features import FEATURE_NAMES, extract_features
from .core.model import AnomalyDetector
from .core.schema import MetricSample, Severity

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)


# ------------------------------------------------------------------ #
# Evaluation engine
# ------------------------------------------------------------------ #


def evaluate_samples(
    detector: AnomalyDetector,
    samples: List[MetricSample],
    *,
    explain: bool = False,
) -> Dict:
    """
    Run the detector on a list of samples and collect metrics.

    Returns dict with: count, detected, scores, severities, explanations.
    """
    detected = 0
    scores: List[float] = []
    severities: Dict[str, int] = {}
    top_explanations: List[Dict] = []

    for s in samples:
        try:
            r = detector.detect(s, explain=explain)
        except Exception:
            continue

        scores.append(r.anomaly_score)
        if r.is_anomaly:
            detected += 1
            sev_name = r.severity.value
            severities[sev_name] = severities.get(sev_name, 0) + 1

            # Collect explanations (first 3 per group)
            if explain and r.explanation and len(top_explanations) < 3:
                contribs = {
                    c.feature_name: round(c.shap_value, 4)
                    for c in r.explanation.contributions[:5]
                }
                top_explanations.append({
                    "score": round(r.anomaly_score, 4),
                    "severity": sev_name,
                    "top_features": contribs,
                })

    return {
        "count": len(scores),
        "detected": detected,
        "recall": detected / max(len(scores), 1),
        "scores": scores,
        "severities": severities,
        "avg_score": float(np.mean(scores)) if scores else 0.0,
        "min_score": float(np.min(scores)) if scores else 0.0,
        "max_score": float(np.max(scores)) if scores else 0.0,
        "std_score": float(np.std(scores)) if scores else 0.0,
        "explanations": top_explanations,
    }


def generate_latex_tables(
    per_attack: Dict[str, Dict],
    normal_stats: Dict,
    model_path: str,
) -> str:
    """Generate LaTeX tables for the research paper."""
    lines = []
    lines.append("% Auto-generated by detection_v2.evaluate_cic")
    lines.append(f"% Model: {model_path}")
    lines.append(f"% Date: {datetime.now().isoformat()}")
    lines.append("")

    # Overall performance table
    lines.append(r"\begin{table}[h]")
    lines.append(r"\centering")
    lines.append(r"\caption{CICDDoS2019 Detection Performance}")
    lines.append(r"\label{tab:cic_performance}")
    lines.append(r"\begin{tabular}{lrrrr}")
    lines.append(r"\hline")
    lines.append(r"\textbf{Attack Type} & \textbf{Samples} & "
                 r"\textbf{Detected} & \textbf{Recall} & "
                 r"\textbf{Avg Score} \\")
    lines.append(r"\hline")

    total_count = 0
    total_detected = 0

    for label in sorted(per_attack):
        if label.lower().strip() == "benign":
            continue
        info = per_attack[label]
        lines.append(
            f"{label} & {info['count']} & {info['detected']} & "
            f"{info['recall']:.1%} & {info['avg_score']:+.4f} \\\\"
        )
        total_count += info["count"]
        total_detected += info["detected"]

    lines.append(r"\hline")
    overall = total_detected / max(total_count, 1)
    lines.append(
        f"\\textbf{{Overall}} & {total_count} & {total_detected} & "
        f"{overall:.1%} & — \\\\"
    )
    lines.append(r"\hline")

    # Normal FPR
    fpr = normal_stats.get("fpr", 0)
    lines.append(
        f"Normal (FPR) & {normal_stats.get('count', 0)} & "
        f"{normal_stats.get('detected', 0)} & "
        f"{fpr:.1%} & {normal_stats.get('avg_score', 0):+.4f} \\\\"
    )

    lines.append(r"\hline")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    lines.append("")

    # Category summary table
    lines.append(r"\begin{table}[h]")
    lines.append(r"\centering")
    lines.append(r"\caption{Detection by Attack Category}")
    lines.append(r"\label{tab:cic_categories}")
    lines.append(r"\begin{tabular}{lrrr}")
    lines.append(r"\hline")
    lines.append(r"\textbf{Category} & \textbf{Samples} & "
                 r"\textbf{Detected} & \textbf{Recall} \\")
    lines.append(r"\hline")

    cat_stats: Dict[str, Dict] = {}
    for label, info in per_attack.items():
        if label.lower().strip() == "benign":
            continue
        cat = categorise_attack(label)
        if cat not in cat_stats:
            cat_stats[cat] = {"count": 0, "detected": 0}
        cat_stats[cat]["count"] += info["count"]
        cat_stats[cat]["detected"] += info["detected"]

    for cat in sorted(cat_stats):
        s = cat_stats[cat]
        r = s["detected"] / max(s["count"], 1)
        lines.append(f"{cat} & {s['count']} & {s['detected']} & {r:.1%} \\\\")

    lines.append(r"\hline")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")

    return "\n".join(lines)


# ------------------------------------------------------------------ #
# Main workflow
# ------------------------------------------------------------------ #


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Evaluate a trained model on CICDDoS2019 dataset",
    )
    parser.add_argument(
        "--model",
        type=str,
        required=True,
        help="Path to the trained model artifact (.pkl)",
    )
    parser.add_argument(
        "--dataset-dir",
        type=str,
        default=None,
        help="Path to CICDDoS2019 parquet/csv files",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Directory to save evaluation report (default: alongside model)",
    )
    parser.add_argument(
        "--max-per-type",
        type=int,
        default=2_000,
        help="Max samples per attack type",
    )
    parser.add_argument(
        "--explain",
        action="store_true",
        help="Generate SHAP explanations for detected attacks",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
    )
    args = parser.parse_args()

    t0 = time.time()
    model_path = Path(args.model)

    # ── 1. Load model ──────────────────────────────────────────────
    logger.info("Loading model: %s", model_path)
    detector = AnomalyDetector(model_path, enable_xai=args.explain)

    # ── 2. Locate dataset ──────────────────────────────────────────
    if args.dataset_dir:
        dataset_dir = Path(args.dataset_dir)
    else:
        # Auto-detect
        for candidate in [
            Path("detection/ml-detector/data/ciddos2019"),
            Path("data/ciddos2019"),
        ]:
            if candidate.exists():
                dataset_dir = candidate
                break
        else:
            raise FileNotFoundError("Cannot find CICDDoS2019 dataset")

    logger.info("Dataset: %s", dataset_dir)
    adapter = CICDDoS2019Adapter(dataset_dir)

    # ── 3. Load data by attack type ────────────────────────────────
    logger.info("Loading data by attack type ...")
    by_attack = adapter.load_by_attack(
        max_per_type=args.max_per_type,
        random_state=args.seed,
    )

    # ── 4. Evaluate each type ──────────────────────────────────────
    per_attack_results: Dict[str, Dict] = {}
    normal_stats: Optional[Dict] = None

    for label in sorted(by_attack):
        samples = by_attack[label]
        logger.info("  Evaluating %-22s  (%d samples) ...", label, len(samples))
        stats = evaluate_samples(detector, samples, explain=args.explain)
        stats["category"] = categorise_attack(label)

        # Remove raw scores from serialisation (too large)
        stats_for_report = {k: v for k, v in stats.items() if k != "scores"}
        per_attack_results[label] = stats_for_report

        if label.lower().strip() == "benign":
            normal_stats = stats_for_report
            normal_stats["fpr"] = stats["recall"]  # "recall" on normal = FPR

    # ── 5. Print summary ──────────────────────────────────────────
    print("\n" + "=" * 72)
    print("  CICDDoS2019 Model Evaluation")
    print("=" * 72)
    print(f"\nModel: {model_path}")
    print(f"Model version: {detector.model_version}")

    if normal_stats:
        print(f"\nNormal traffic FPR: {normal_stats['fpr']:.4f} "
              f"({normal_stats['fpr']*100:.1f}%)")

    print(f"\n{'Label':<22s}  {'Cat':<14s}  {'N':>5s}  "
          f"{'Det':>5s}  {'Recall':>7s}  {'AvgScr':>8s}  {'Severity':>15s}")
    print("-" * 80)

    total_count = total_det = 0
    for label in sorted(per_attack_results):
        if label.lower().strip() == "benign":
            continue
        info = per_attack_results[label]
        sev_str = ", ".join(f"{k}:{v}" for k, v in sorted(info.get("severities", {}).items()))
        print(
            f"{label:<22s}  {info.get('category',''):<14s}  "
            f"{info['count']:5d}  {info['detected']:5d}  "
            f"{info['recall']:7.1%}  {info['avg_score']:+8.4f}  "
            f"{sev_str:>15s}"
        )
        total_count += info["count"]
        total_det += info["detected"]

    print("-" * 80)
    overall = total_det / max(total_count, 1)
    print(f"{'TOTAL':<22s}  {'':14s}  {total_count:5d}  "
          f"{total_det:5d}  {overall:7.1%}")
    print("=" * 72)

    # ── 6. Save outputs ───────────────────────────────────────────
    output_dir = Path(args.output_dir) if args.output_dir else model_path.parent
    output_dir.mkdir(parents=True, exist_ok=True)

    # JSON report
    report = {
        "timestamp": datetime.now().isoformat(),
        "model_path": str(model_path),
        "model_version": detector.model_version,
        "dataset_dir": str(dataset_dir),
        "per_attack": per_attack_results,
        "overall_attack_recall": overall,
        "normal_fpr": normal_stats["fpr"] if normal_stats else None,
        "elapsed_seconds": time.time() - t0,
    }
    report_path = output_dir / "cic_eval_report.json"
    with open(report_path, "w") as f:
        json.dump(report, f, indent=2, default=str)
    logger.info("JSON report: %s", report_path)

    # LaTeX tables
    latex = generate_latex_tables(
        per_attack_results,
        normal_stats or {},
        str(model_path),
    )
    latex_path = output_dir / "cic_eval_tables.tex"
    with open(latex_path, "w") as f:
        f.write(latex)
    logger.info("LaTeX tables: %s", latex_path)

    logger.info("Done in %.1fs", time.time() - t0)


if __name__ == "__main__":
    main()
